name = "ens-reverse-records"
main = "packages/api/src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "packages/frontend/dist"
not_found_handling = "single-page-application"
